import type { Locale } from './site';

// Editorial imagery, keyed by translationKey. Files generated by
// scripts/img.ts (720×1080 webp) from ./stock-originals/.
export type Img = { src: string; alt: Record<Locale, string> };

export const HERO_IMG: Img = {
  src: '/img/hero.webp',
  alt: {
    nl: 'Detail van zwarte kanten lingerie in warm avondlicht',
    en: 'Close-up of black lace lingerie in warm evening light',
  },
};

export const ARTICLE_IMG: Record<string, Img> = {
  'is-escort-legal': {
    src: '/img/law.webp',
    alt: {
      nl: 'Model poseert in een strak verlichte studio',
      en: 'Model posing in a starkly lit studio',
    },
  },
  'escort-prices': {
    src: '/img/prices.webp',
    alt: {
      nl: 'Portret van een model in avondkleding',
      en: 'Portrait of a model in evening wear',
    },
  },
  'spot-fakes': {
    src: '/img/fakes.webp',
    alt: {
      nl: 'Model in tegenlicht, gezicht deels zichtbaar',
      en: 'Backlit model, face partly visible',
    },
  },
  'etiquette-first-time': {
    src: '/img/etiquette.webp',
    alt: {
      nl: 'Ontspannen huiselijke setting met koffie',
      en: 'Relaxed domestic setting with coffee',
    },
  },
  'escort-amsterdam': {
    src: '/img/amsterdam.webp',
    alt: {
      nl: 'Blauw verlichte kamer met barok behang',
      en: 'Blue-lit room with baroque wallpaper',
    },
  },
  'best-escort-sites': {
    src: '/img/ranking.webp',
    alt: {
      nl: 'Model in stedelijke omgeving',
      en: 'Model in an urban setting',
    },
  },
  methodology: {
    src: '/img/methodology.webp',
    alt: {
      nl: 'Minimalistisch studioportret',
      en: 'Minimalist studio portrait',
    },
  },
  'kinky-review': {
    src: '/img/kinky.webp',
    alt: {
      nl: 'Portret met dramatische verlichting',
      en: 'Portrait with dramatic lighting',
    },
  },
  'intimate-review': {
    src: '/img/intimate.webp',
    alt: {
      nl: 'Ingetogen editorial portret',
      en: 'Understated editorial portrait',
    },
  },
  'forms-difference': {
    src: '/img/forms.webp',
    alt: {
      nl: 'Portret in gedempt binnenlicht',
      en: 'Portrait in muted indoor light',
    },
  },
  'client-rules': {
    src: '/img/client-rules.webp',
    alt: {
      nl: 'Model in formele studio-omgeving',
      en: 'Model in a formal studio setting',
    },
  },
  'municipal-rules': {
    src: '/img/municipalities.webp',
    alt: {
      nl: 'Silhouet tegen stedelijke achtergrond',
      en: 'Silhouette against an urban backdrop',
    },
  },
  'worker-safety': {
    src: '/img/worker-safety.webp',
    alt: {
      nl: 'Rustig portret in zacht licht',
      en: 'Calm portrait in soft light',
    },
  },
  'verification-explained': {
    src: '/img/verification.webp',
    alt: {
      nl: 'Portret met scherpe, heldere belichting',
      en: 'Portrait with sharp, clear lighting',
    },
  },
  'kinky-vs-intimate': {
    src: '/img/versus.webp',
    alt: {
      nl: 'Contrastrijk studioportret',
      en: 'High-contrast studio portrait',
    },
  },
  'sexjobs-review': {
    src: '/img/sexjobs.webp',
    alt: {
      nl: 'Portret met warme avondtinten',
      en: 'Portrait in warm evening tones',
    },
  },
  'escort-rotterdam': {
    src: '/img/rotterdam.webp',
    alt: {
      nl: 'Model in moderne stedelijke setting',
      en: 'Model in a modern urban setting',
    },
  },
  'escort-den-haag': {
    src: '/img/den-haag.webp',
    alt: {
      nl: 'Elegant portret in natuurlijk licht',
      en: 'Elegant portrait in natural light',
    },
  },
  'escort-utrecht': {
    src: '/img/utrecht.webp',
    alt: {
      nl: 'Portret in intieme binnenruimte',
      en: 'Portrait in an intimate interior',
    },
  },
  'amsterdam-tourist': {
    src: '/img/tourist.webp',
    alt: {
      nl: 'Avondportret in stadslicht',
      en: 'Evening portrait in city light',
    },
  },
  glossary: {
    src: '/img/glossary.webp',
    alt: {
      nl: 'Minimalistisch portret in daglicht',
      en: 'Minimalist portrait in daylight',
    },
  },
  'faq-hub': {
    src: '/img/faq.webp',
    alt: {
      nl: 'Portret met rustige, neutrale achtergrond',
      en: 'Portrait with a calm, neutral background',
    },
  },
  'redlights-review': {
    src: '/img/redlights.webp',
    alt: {
      nl: 'Portret in warm binnenlicht',
      en: 'Portrait in warm indoor light',
    },
  },
  'boys4u-review': {
    src: '/img/boys4u.webp',
    alt: {
      nl: 'Sfeervolle close-up in avondlicht',
      en: 'Atmospheric close-up in evening light',
    },
  },
  'eurogirlsescort-review': {
    src: '/img/eurogirlsescort.webp',
    alt: {
      nl: 'Editorial portret met stedelijke achtergrond',
      en: 'Editorial portrait with urban backdrop',
    },
  },
  'escortnews-review': {
    src: '/img/escortnews.webp',
    alt: {
      nl: 'Portret met gedempte studioverlichting',
      en: 'Portrait in muted studio lighting',
    },
  },
  'tryst-review': {
    src: '/img/tryst.webp',
    alt: {
      nl: 'Portret in natuurlijk daglicht',
      en: 'Portrait in natural daylight',
    },
  },
  'escorthub-review': {
    src: '/img/escorthub.webp',
    alt: {
      nl: 'Portret met dramatisch licht en schaduw',
      en: 'Portrait with dramatic light and shadow',
    },
  },
  'all-escort-sites': {
    src: '/img/all-sites.webp',
    alt: {
      nl: 'Avondportret in de stad',
      en: 'Evening portrait in the city',
    },
  },
};
