import type { Locale } from './site';

// Editorial imagery, keyed by translationKey. Files generated by
// scripts/img.ts (720×1080 webp) from ./stock-originals/.
export type Img = { src: string; alt: Record<Locale, string> };

export const HERO_IMG: Img = {
  src: '/img/hero.webp',
  alt: {
    nl: 'Detail van zwarte kanten lingerie in warm avondlicht',
    en: 'Close-up of black lace lingerie in warm evening light',
  },
};

export const ARTICLE_IMG: Record<string, Img> = {
  'is-escort-legal': {
    src: '/img/law.webp',
    alt: {
      nl: 'Model poseert in een strak verlichte studio',
      en: 'Model posing in a starkly lit studio',
    },
  },
  'escort-prices': {
    src: '/img/prices.webp',
    alt: {
      nl: 'Portret van een model in avondkleding',
      en: 'Portrait of a model in evening wear',
    },
  },
  'spot-fakes': {
    src: '/img/fakes.webp',
    alt: {
      nl: 'Model in tegenlicht, gezicht deels zichtbaar',
      en: 'Backlit model, face partly visible',
    },
  },
  'etiquette-first-time': {
    src: '/img/etiquette.webp',
    alt: {
      nl: 'Ontspannen huiselijke setting met koffie',
      en: 'Relaxed domestic setting with coffee',
    },
  },
  'escort-amsterdam': {
    src: '/img/amsterdam.webp',
    alt: {
      nl: 'Blauw verlichte kamer met barok behang',
      en: 'Blue-lit room with baroque wallpaper',
    },
  },
  'best-escort-sites': {
    src: '/img/ranking.webp',
    alt: {
      nl: 'Model in stedelijke omgeving',
      en: 'Model in an urban setting',
    },
  },
  methodology: {
    src: '/img/methodology.webp',
    alt: {
      nl: 'Minimalistisch studioportret',
      en: 'Minimalist studio portrait',
    },
  },
  'kinky-review': {
    src: '/img/kinky.webp',
    alt: {
      nl: 'Portret met dramatische verlichting',
      en: 'Portrait with dramatic lighting',
    },
  },
  'intimate-review': {
    src: '/img/intimate.webp',
    alt: {
      nl: 'Ingetogen editorial portret',
      en: 'Understated editorial portrait',
    },
  },
};
